### PR TITLE
New PR for linters testing purpose

### PR DESCRIPTION
**Pull request by lucianosarno**
As suggested by the last TSE, we have closed the previous PR and created a new one, to check if the linters files are working fine.
This is the last required change for this project.

### CODE REVIEW

**Comment by lucianosarno** [comment]
Here we have a problem:

When we run rubocop in local environment, we have the offenses:
'Missing frozen string literal comment'

But when we include the required comment, and run rubocop on web version, we have the offenses:
'Unnecessary frozen string literal comment'

So please, we need some help on this.

**Review by kubilaycaglayan — CHANGES_REQUESTED** [review]
Hello Team 👋
Status: Changes Required ♻️

Great job so far! All your tests are passing(5) 👍👏🎯
Let's cover a few details together to make this project better ⏬

## Tests

- [x] All the public methods of the classes implemented in project OOP are tested ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/all_tic_tac_toe.png)  from  [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

💡 Please add tests for the `game#winning_board` method.

💡 For the Player class, please add a test that checks the instance variable's `name` property.

#### That's it, team. After making the changes, you can request another code review request 😊

With all my respect 🙏
> Kubilay Caglayan | Technical Support Engineer

**Comment by kubilaycaglayan** [comment]
> Here we have a problem:
> 
> When we run rubocop in local environment, we have the offenses:
> 'Missing frozen string literal comment'
> 
> But when we include the required comment, and run rubocop on web version, we have the offenses:
> 'Unnecessary frozen string literal comment'
> 
> So please, we need some help on this.

Hope this helps 🎉
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment

**Review by voscarmv — APPROVED** [review]
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

**[OPTIONAL]**

- Please remove the `additional_method` from `player.rb` (it seems to be doing nothing anywhere else in the game).
- Please try to reduce the line length in your `game_spec.rb` instead of just deactivating rubocop.

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
